### ISSUE TITLE
Android App Crashing

### ISSUE THREAD

**Issue by itsmebharat** [jepiqueau/jeep#22]
Plugin is throwing error on android , i have added "add(CapacitorVideoPlayer.class);" in MainActivity class
Below is the error, kindly suggest how to fix.

`2020-07-26 00:59:25.864 6011-6011/com.mydomain E/FragmentManager: No view found for id 0x7f0800a2 (com.mydomain:id/frameLayout) for fragment FullscreenExoPlayerFragment{973798c #1 id=0x7f0800a2}
2020-07-26 00:59:25.864 6011-6011/com.mydomain E/FragmentManager: Activity state:
2020-07-26 00:59:25.865 6011-6011/com.mydomain E/FragmentManager:   Local Activity 6eae527 State:
2020-07-26 00:59:25.865 6011-6011/com.mydomain E/FragmentManager:     mResumed=true mStopped=false mFinished=false
2020-07-26 00:59:25.865 6011-6011/com.mydomain E/FragmentManager:     mChangingConfigurations=false
2020-07-26 00:59:25.865 6011-6011/com.mydomain E/FragmentManager:     mCurrentConfig={1.0 310mcc260mnc [en_US] ldltr sw392dp w392dp h713dp 440dpi nrml long port finger qwerty/v/v -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 2028) mAppBounds=Rect(0, 0 - 1080, 2028) mWindowingMode=fullscreen mActivityType=standard} s.37}
2020-07-26 00:59:25.865 6011-6011/com.mydomain E/FragmentManager:     mLoadersStarted=true
2020-07-26 00:59:25.865 6011-6011/com.mydomain E/FragmentManager:     Active Fragments in 37b98d5:
2020-07-26 00:59:25.865 6011-6011/com.mydomain E/FragmentManager:       #0: ReportFragment{def28ea #0 androidx.lifecycle.LifecycleDispatcher.report_fragment_tag}
2020-07-26 00:59:25.865 6011-6011/com.mydomain E/FragmentManager:         mFragmentId=#0 mContainerId=#0 mTag=androidx.lifecycle.LifecycleDispatcher.report_fragment_tag
2020-07-26 00:59:25.865 6011-6011/com.mydomain E/FragmentManager:         mState=5 mIndex=0 mWho=android:fragment:0 mBackStackNesting=0
2020-07-26 00:59:25.865 6011-6011/com.mydomain E/FragmentManager:         mAdded=true mRemoving=false mFromLayout=false mInLayout=false
2020-07-26 00:59:25.866 6011-6011/com.mydomain E/FragmentManager:         mHidden=false mDetached=false mMenuVisible=true mHasMenu=false
2020-07-26 00:59:25.866 6011-6011/com.mydomain E/FragmentManager:         mRetainInstance=false mRetaining=false mUserVisibleHint=true
2020-07-26 00:59:25.866 6011-6011/com.mydomain E/FragmentManager:         mFragmentManager=FragmentManager{37b98d5 in HostCallbacks{c47e7db}}
2020-07-26 00:59:25.866 6011-6011/com.mydomain E/FragmentManager:         mHost=
2020-07-26 00:59:25.867 6011-6011/com.mydomain E/FragmentManager: android.app.Activity$HostCallbacks@c47e7db
2020-07-26 00:59:25.867 6011-6011/com.mydomain E/FragmentManager:         Child FragmentManager{1a4a278 in ReportFragment{def28ea}}:
2020-07-26 00:59:25.867 6011-6011/com.mydomain E/FragmentManager:           FragmentManager misc state:
2020-07-26 00:59:25.867 6011-6011/com.mydomain E/FragmentManager:             mHost=android.app.Activity$HostCallbacks@c47e7db
2020-07-26 00:59:25.867 6011-6011/com.mydomain E/FragmentManager:             mContainer=android.app.Fragment$1@d69ed51
2020-07-26 00:59:25.867 6011-6011/com.mydomain E/FragmentManager:             mParent=ReportFragment{def28ea #0 androidx.lifecycle.LifecycleDispatcher.report_fragment_tag}
2020-07-26 00:59:25.867 6011-6011/com.mydomain E/FragmentManager:             mCurState=5 mStateSaved=false mDestroyed=false
2020-07-26 00:59:25.867 6011-6011/com.mydomain E/FragmentManager:       #1: FullscreenExoPlayerFragment{973798c #1 id=0x7f0800a2}
2020-07-26 00:59:25.867 6011-6011/com.mydomain E/FragmentManager:         mFragmentId=#7f0800a2 mContainerId=#7f0800a2 mTag=null
2020-07-26 00:59:25.867 6011-6011/com.mydomain E/FragmentManager:         mState=1 mIndex=1 mWho=android:fragment:1 mBackStackNesting=0
2020-07-26 00:59:25.867 6011-6011/com.mydomain E/FragmentManager:         mAdded=true mRemoving=false mFromLayout=false mInLayout=false
2020-07-26 00:59:25.867 6011-6011/com.mydomain E/FragmentManager:         mHidden=false mDetached=false mMenuVisible=true mHasMenu=false
2020-07-26 00:59:25.867 6011-6011/com.mydomain E/FragmentManager:         mRetainInstance=false mRetaining=false mUserVisibleHint=true
2020-07-26 00:59:25.868 6011-6011/com.mydomain E/FragmentManager:         mFragmentManager=FragmentManager{37b98d5 in HostCallbacks{c47e7db}}
2020-07-26 00:59:25.868 6011-6011/com.mydomain E/FragmentManager:         mHost=android.app.Activity$HostCallbacks@c47e7db
2020-07-26 00:59:25.868 6011-6011/com.mydomain E/FragmentManager:     Added Fragments:
2020-07-26 00:59:25.868 6011-6011/com.mydomain E/FragmentManager:       #0: 
2020-07-26 00:59:25.869 6011-6011/com.mydomain E/FragmentManager: ReportFragment{def28ea #0 androidx.lifecycle.LifecycleDispatcher.report_fragment_tag}
2020-07-26 00:59:25.869 6011-6011/com.mydomain E/FragmentManager:       #1: FullscreenExoPlayerFragment{973798c #1 id=0x7f0800a2}
2020-07-26 00:59:25.869 6011-6011/com.mydomain E/FragmentManager:     FragmentManager misc state:
2020-07-26 00:59:25.869 6011-6011/com.mydomain E/FragmentManager:       mHost=android.app.Activity$HostCallbacks@c47e7db
2020-07-26 00:59:25.869 6011-6011/com.mydomain E/FragmentManager:       mContainer=android.app.Activity$HostCallbacks@c47e7db
2020-07-26 00:59:25.869 6011-6011/com.mydomain E/FragmentManager:       mCurState=5 mStateSaved=false mDestroyed=false
2020-07-26 00:59:25.869 6011-6011/com.mydomain E/FragmentManager:   ViewRoot:
2020-07-26 00:59:25.869 6011-6011/com.mydomain E/FragmentManager:     mAdded=true mRemoved=false
2020-07-26 00:59:25.869 6011-6011/com.mydomain E/FragmentManager:     mConsumeBatchedInputScheduled=false
2020-07-26 00:59:25.869 6011-6011/com.mydomain E/FragmentManager:     mConsumeBatchedInputImmediatelyScheduled=false
2020-07-26 00:59:25.869 6011-6011/com.mydomain E/FragmentManager:     mPendingInputEventCount=0
2020-07-26 00:59:25.869 6011-6011/com.mydomain E/FragmentManager:     mProcessInputEventsScheduled=false
2020-07-26 00:59:25.870 6011-6011/com.mydomain E/FragmentManager:     mTraversalScheduled=false    mIsAmbientMode=false
2020-07-26 00:59:25.870 6011-6011/com.mydomain E/FragmentManager:     android.view.ViewRootImpl$NativePreImeInputStage: mQueueLength=0
2020-07-26 00:59:25.870 6011-6011/com.mydomain E/FragmentManager:     android.view.ViewRootImpl$ImeInputStage: mQueueLength=0
2020-07-26 00:59:25.870 6011-6011/com.mydomain E/FragmentManager:     android.view.ViewRootImpl$NativePostImeInputStage: mQueueLength=0
2020-07-26 00:59:25.870 6011-6011/com.mydomain E/FragmentManager:   Choreographer:
2020-07-26 00:59:25.870 6011-6011/com.mydomain E/FragmentManager:     mFrameScheduled=true
2020-07-26 00:59:25.870 6011-6011/com.mydomain E/FragmentManager:     mLastFrameTime=62552453 (15 ms ago)
2020-07-26 00:59:25.870 6011-6011/com.mydomain E/FragmentManager:   View Hierarchy:
2020-07-26 00:59:25.870 6011-6011/com.mydomain E/FragmentManager:     DecorView@a0ee9b6[MainActivity]
2020-07-26 00:59:25.870 6011-6011/com.mydomain E/FragmentManager:       android.widget.LinearLayout{c5326b7 V.E...... ........ 0,0-1080,2028}
2020-07-26 00:59:25.871 6011-6011/com.mydomain E/FragmentManager:         android.view.ViewStub{dbd6e24 G.E...... ......I. 0,0-0,0 #102018a android:id/action_mode_bar_stub}
2020-07-26 00:59:25.871 6011-6011/com.mydomain E/FragmentManager:         android.widget.FrameLayout{50f0d8d V.E...... ........ 0,66-1080,2028}
2020-07-26 00:59:25.871 6011-6011/com.mydomain E/FragmentManager:           androidx.appcompat.widget.FitWindowsLinearLayout{597eb42 V.E...... ........ 0,0-1080,1962 #7f08002f app:id/action_bar_root}
2020-07-26 00:59:25.871 6011-6011/com.mydomain E/FragmentManager:             androidx.appcompat.widget.ViewStubCompat{2697753 G.E...... ......I. 0,0-0,0 #7f08003a app:id/action_mode_bar_stub}
2020-07-26 00:59:25.871 6011-6011/com.mydomain E/FragmentManager:             androidx.appcompat.widget.ContentFrameLayout{6754890 V.E...... ........ 0,0-1080,1962 #1020002 android:id/content}
2020-07-26 00:59:25.871 6011-6011/com.mydomain E/FragmentManager:               androidx.coordinatorlayout.widget.CoordinatorLayout{b6bf589 V.E...... ........ 0,0-1080,1962}
2020-07-26 00:59:25.871 6011-6011/com.mydomain E/FragmentManager:                 android.webkit.WebView{3be5db4 VFEDHVC.. .F...... 0,0-1080,1962 #7f080155 app:id/webview}
2020-07-26 00:59:25.871 6011-6011/com.mydomain E/FragmentManager:       android.view.View{2bd798e V.ED..... ........ 0,2028-1080,2160 #1020030 android:id/navigationBarBackground}
2020-07-26 00:59:25.871 6011-6011/com.mydomain E/FragmentManager:       android.view.View{78a35af V.ED..... ........ 0,0-1080,66 #102002f android:id/statusBarBackground}
2020-07-26 00:59:25.877 6011-6011/com.mydomain E/FragmentManager:   Looper (main, tid 2) {db139e9}
2020-07-26 00:59:25.877 6011-6011/com.mydomain E/FragmentManager:     (Total messages: 0, polling=false, quitting=false)
2020-07-26 00:59:25.877 6011-6011/com.mydomain E/FragmentManager:   Autofill Compat Mode: false
2020-07-26 00:59:25.877 6011-6011/com.mydomain E/FragmentManager:   AutofillManager:
2020-07-26 00:59:25.878 6011-6011/com.mydomain E/FragmentManager:     sessionId: -2147483648
2020-07-26 00:59:25.878 6011-6011/com.mydomain E/FragmentManager:     state: UNKNOWN
2020-07-26 00:59:25.878 6011-6011/com.mydomain E/FragmentManager:     context: com.mydomain.MainActivity@6eae527
2020-07-26 00:59:25.878 6011-6011/com.mydomain E/FragmentManager:     client: com.mydomain.MainActivity@6eae527
2020-07-26 00:59:25.878 6011-6011/com.mydomain E/FragmentManager:     enabled: true
2020-07-26 00:59:25.878 6011-6011/com.mydomain E/FragmentManager:     hasService: true
2020-07-26 00:59:25.878 6011-6011/com.mydomain E/FragmentManager:     hasCallback: true
2020-07-26 00:59:25.878 6011-6011/com.mydomain E/FragmentManager:     onInvisibleCalled false
2020-07-26 00:59:25.878 6011-6011/com.mydomain E/FragmentManager:     last autofilled data: null
2020-07-26 00:59:25.878 6011-6011/com.mydomain E/FragmentManager:     tracked views: null
2020-07-26 00:59:25.878 6011-6011/com.mydomain E/FragmentManager:     fillable ids: null
2020-07-26 00:59:25.878 6011-6011/com.mydomain E/FragmentManager:     entered ids: null
2020-07-26 00:59:25.878 6011-6011/com.mydomain E/FragmentManager:     save trigger id: null
2020-07-26 00:59:25.878 6011-6011/com.mydomain E/FragmentManager:     save on finish(): false
2020-07-26 00:59:25.878 6011-6011/com.mydomain E/FragmentManager:     compat mode enabled: false
2020-07-26 00:59:25.878 6011-6011/com.mydomain E/FragmentManager:     debug: false verbose: false
2020-07-26 00:59:25.879 6011-6011/com.mydomain E/FragmentManager:   ResourcesManager:
2020-07-26 00:59:25.879 6011-6011/com.mydomain E/FragmentManager:     cached apks: total=3 created=0 evicted=0 hit=4 miss=3 max=3
2020-07-26 00:59:25.879 6011-6011/com.mydomain E/FragmentManager:     total apks: 3
2020-07-26 00:59:25.879 6011-6011/com.mydomain E/FragmentManager:     resources: 3
2020-07-26 00:59:25.879 6011-6011/com.mydomain E/FragmentManager:     resource impls: 3
2020-07-26 00:59:25.879 6011-6011/com.mydomain E/FragmentManager:   Local FragmentActivity 6eae527 State:
2020-07-26 00:59:25.879 6011-6011/com.mydomain E/FragmentManager:     mCreated=true mResumed=true mStopped=false  FragmentManager misc state:
2020-07-26 00:59:25.879 6011-6011/com.mydomain E/FragmentManager:     mHost=androidx.fragment.app.FragmentActivity$HostCallbacks@68e5dbc
2020-07-26 00:59:25.879 6011-6011/com.mydomain E/FragmentManager:     mContainer=androidx.fragment.app.FragmentActivity$HostCallbacks@68e5dbc
2020-07-26 00:59:25.879 6011-6011/com.mydomain E/FragmentManager:     mCurState=4 mStateSaved=
2020-07-26 00:59:25.879 6011-6011/com.mydomain E/FragmentManager: false mStopped=false mDestroyed=false
2020-07-26 00:59:25.880 6011-6011/com.mydomain E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mydomain, PID: 6011
    java.lang.IllegalArgumentException: No view found for id 0x7f0800a2 (com.mydomain:id/frameLayout) for fragment FullscreenExoPlayerFragment{973798c #1 id=0x7f0800a2}
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1292)
        at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2426)
        at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2205)
        at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2161)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2062)
        at android.app.FragmentManagerImpl$1.run(FragmentManager.java:738)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

**Comment by itsmebharat** [comment]
Sorry I post this issue in the wrong repo it suppose to related to

https://github.com/jepiqueau/capacitor-video-player
